### PR TITLE
fix: importing via magick++ for version >= 7.0.1

### LINKED ISSUE #3331: Import of raster work is broken in Master
**Description**
I was preparing to test rodolforg's Curve Warp port and before I got to it I noticed that import of raster images (pngs, jpegs) is broken. For example, an imported png would look like this:
Test

While pngs are a complete mess, jpegs are imported almost correctly but have wrong colors.

**To Reproduce**
On empty canvas, import any png image through "File->Import". It will look similar to the image above with weird lines and wrong colors.

**Expected behavior**
It would have been nice if all supported image formats would display correctly.

**System information:**
Windows 10 Pro, version 2004.
Commit: 7f39534c86faf005dae4ded1ac313d97e353c624
Something broke very recently I believe.

### PR DESCRIPTION
**Pull request by rodolforg**
There was an undefined behavior due to multiple increment of same variable in multiple function arguments. - sorry

fix #3331

### CODE REVIEW

File: synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp [hunk 1]
```diff
@@ -128,33 +128,43 @@ magickpp_mptr::get_frame(synfig::Surface& surface, const synfig::RendDesc& /*ren
 		const auto height = image.size().height();
 		surface.set_wh(width, height);
 
-		image.type(Magick::TrueColorType);
-// Sadly Magick++ API is a mess with namespaces...
-{
-	using namespace Magick;
-	using namespace MagickCore;
+#if MagickLibVersion >= 0x701 // MAGICKCORE_CHECK_VERSION(7,0,0) does not work!
+		const bool has_alpha = image.alpha();
```
Comment (ice0) [inline synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp:132]: I suggest moving the ImageType here as well. In this case, we group all the overrides together:
```
#if MagickLibVersion >= 0x701 // MAGICKCORE_CHECK_VERSION(7,0,0) does not work!
		const bool has_alpha = image.alpha();
		constexpr MagickCore::ImageType TrueColorAlphaType = Magick::TrueColorAlphaType;
#else
		const bool has_alpha = image.matte();
		constexpr MagickCore::ImageType TrueColorAlphaType = Magick::TrueColorMatteType;
#endif
```

File: synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp [hunk 2]
```diff
@@ -128,33 +128,43 @@ magickpp_mptr::get_frame(synfig::Surface& surface, const synfig::RendDesc& /*ren
...
+// Sadly Magick++ API is a mess with namespaces...
+{
+	using namespace Magick;
+	using namespace MagickCore;
+
 
 		constexpr synfig::Color::value_type factor = QuantumRange;
 
 		for (size_t y = 0, i = 0; y < height; ++y) {
 			for (size_t x = 0; x < width; ++x, ++i) {
```
Comment (ice0) [inline synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp:161]: It looks like we can make this code clearer by taking `++i` out of the loop:
3 and 4 constants should be clearer than 2 and 3.
```
		for (size_t y = 0, i = 0; y < height; ++y) {
			for (size_t x = 0; x < width; ++x) {
#if MagickLibVersion >= 0x701 // MAGICKCORE_CHECK_VERSION(7,0,0) does not work!
				if (has_alpha) {
					surface[y][x] = synfig::Color(packet[i] / factor, packet[i+1] / factor, packet[i+2] / factor, packet[i+3] / factor);
					i += 4;
				} else {
					surface[y][x] = synfig::Color(packet[i] / factor, packet[i+1] / factor, packet[i+2] / factor, 1.);
					i += 3;
				}
#else
				const auto& color = packet[++i];
				if (has_alpha)
					surface[y][x] = synfig::Color(color.red / factor, color.green / factor, color.blue / factor, 1. - color.opacity / factor);
				else
					surface[y][x] = synfig::Color(color.red / factor, color.green / factor, color.blue / factor, 1.);
#endif
```

File: synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp (hunk 1 above)
Comment (rodolforg) [reply synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp:132]: Done

File: synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp (hunk 2 above)
Comment (rodolforg) [reply synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp]: Indeed, it's way better!
I just changed the pre-increment to post-increment on `else` branch, as it would skip `packet[0]` otherwise

Comment (ice0) [reply synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp]: > as it would skip packet[0] otherwise

Good catch!

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!
