### PR TITLE
[Synfig Studio] Fixed crash when user drags a group to a child group

### LINKED ISSUE #2110: Crashes when user (wrongly) try to move a group layer into a child group
**Describe the bug**
Synfig Studio doesn't check if a group layer is being moved into a child group layer.

**To Reproduce**
1. Create a Group layer (Group A in the screenshot below)
2. Create a Group layer named Group B
3. By dragging and dropping, move the Group B into Group A (as shown in screenshot below)
4. Now drag Group A to inside Group B.
5. It crashes.

Captura de tela de 2021-04-16 15-59-09

**Expected behavior**
Synfig should ignore this type of layer movement.

**Desktop (please complete the following information):**
 - OS: any
 - OS version: any
 - Synfig version: 1.4.0

### PR DESCRIPTION
**Pull request by rodolforg**
… group

fix #2110

### CODE REVIEW

File: synfig-studio/src/gui/trees/layertreestore.cpp [hunk 1]
```diff
@@ -511,23 +527,55 @@ LayerTreeStore::drag_data_delete_vfunc (const TreeModel::Path& /*path*/)
...
+				TreeModel::Row parent_row = *parent_iter;
+				if (RECORD_TYPE_LAYER == static_cast<RecordType>(parent_row[model.record_type]))
+				{
+					Canvas::Handle target_canvas = static_cast<Canvas::Handle>(parent_row[model.contained_canvas]);
+					if (target_canvas)
+					{
+						// don't let user drop a group layer into a child of its own
+
+						// list of ancestors of dest
+						std::vector<Layer::LooseHandle> dest_layer_tree;
```
Comment (ice0) [inline synfig-studio/src/gui/trees/layertreestore.cpp:557]: I suggest to simplify this part:
```
	// don't let user drop a group layer into a child of its own

	synfigapp::SelectionManager::LayerList dragged_layers;
	retrieve_layers_from_dragging(selection_data, dragged_layers);

	Layer::Handle parent_layer = parent_row[model.layer];
	do {
		for (const auto& drag_layer : dragged_layers) {
			if (parent_layer == drag_layer) return false;
		}
	} while (parent_layer = parent_layer->get_parent_paste_canvas_layer());

	return true;
```

Comment (rodolforg) [reply synfig-studio/src/gui/trees/layertreestore.cpp]: Done

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!
