### PR TITLE
Fix bone width handle visibility

### LINKED ISSUE #2088: [Skeleton Tool] Width control points are not displayed when creating Skeleton Deformation
**Describe the bug**
Try to use Bone Tool to create Skeleton deformation layer. You will see that there are no Width Control points displayed when you create first (and sometimes second) bone. But on third bone control points suddenly become visible.

This behavior shown in this video - https://youtu.be/2ru_D7Hx2Dg

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - OS version: Mint 19
 - Synfig version: master branch - ef901e498d8a9653b06971f034b9641946ba4f50

### PR DESCRIPTION
**Pull request by rodolforg**
fix #2088

### CODE REVIEW

File: synfig-studio/src/gui/states/state_bone.cpp [hunk 1]
```diff
@@ -131,26 +131,28 @@ class studio::StateBone_Context : public sigc::trackable
 
 	void set_active_bone(ValueNode::Handle value_node);
 
+	static constexpr Real default_angle = 3.14159265358979323846/2;
```
Comment (ice0) [inline synfig-studio/src/gui/states/state_bone.cpp:134]: Is there a reason not to use `M_PI` here? I am asking because I planned to replace all these values with named definitions/constants.

Comment (rodolforg) [reply synfig-studio/src/gui/states/state_bone.cpp:134]: Yes: I just forgot it :)

File: synfig-studio/src/gui/states/state_bone.cpp [hunk 2]
```diff
@@ -428,13 +428,13 @@ StateBone_Context::StateBone_Context(CanvasView *canvas_view) :
 	Layer::Handle layer = get_canvas_interface()->get_selection_manager()->get_selected_layer();
 
 	if(Layer_SkeletonDeformation::Handle::cast_dynamic(layer)){
-		get_work_area()->set_type_mask(get_work_area()->get_type_mask() - (Duck::TYPE_TANGENT | Duck::TYPE_WIDTH));
+		get_work_area()->set_type_mask(get_work_area()->get_type_mask() - Duck::TYPE_TANGENT | (Duck::TYPE_WIDTH | Duck::TYPE_WIDTHPOINT_POSITION));
```
Comment (ice0) [inline synfig-studio/src/gui/states/state_bone.cpp:433]: I think it's better to use bit logic here, just to avoid getting unpredictable results in case when some flag is not enabled. 
I made an example showing this: https://godbolt.org/z/T494be75z

Comment (rodolforg) [reply synfig-studio/src/gui/states/state_bone.cpp:433]: Oh, as `-` was used everywhere, I thought there was an overload operator method.
Fixing it.

Comment (rodolforg) [reply synfig-studio/src/gui/states/state_bone.cpp:433]: Argh, it doesn't build without casting :P 
`get_work_area()->set_type_mask(Duck::Type(get_work_area()->get_type_mask() & ~(Duck::TYPE_TANGENT | Duck::TYPE_WIDTH | Duck::TYPE_WIDTHPOINT_POSITION)));`
or
`get_work_area()->set_type_mask(get_work_area()->get_type_mask() & Duck::Type(~(Duck::TYPE_TANGENT | Duck::TYPE_WIDTH | Duck::TYPE_WIDTHPOINT_POSITION)));`

Comment (rodolforg) [reply synfig-studio/src/gui/states/state_bone.cpp:433]: Oh it is overloaded: 
https://github.com/synfig/synfig/blob/310aaad378224b6db22cc0639e66e36dfc45368c/synfig-studio/src/gui/duck.h#L462-L465

**Comment by rodolforg** [comment]
Rebased

File: synfig-studio/src/gui/states/state_bone.cpp (hunk 2 above)
Comment (ice0) [reply synfig-studio/src/gui/states/state_bone.cpp:433]: Ok.

**Review by ice0 — APPROVED** [review]

**Comment by morevnaproject** [comment]
It works now! Thank you!
