### PR TITLE
Fix for issue #949: File not saved properly after executing a plugin

### LINKED ISSUE #949: File not saved properly after executing a plugin
**Synfig version & platform**:
Master branch, commit 2b54ed842195016f44c246658f092729dea037bd

**Issue description**:
After executing any plugin (via "Plug-Ins" menu) file is not saved to its location anymore.

Steps to reproduce:
1. Start Synfig and create new document
2. Create a circle.
3. Save document to `/tmp/test.sifz`
4. Choose "Plug-Ins" -> "Add Skeleton (Simple)"
5. After executing a plugin a stickman (human figure) will appear on workarea (above the circle).
6. Save file.
7. Close file.
8. Open `/tmp/test.sifz` file
9. -> You will see only circle there (no stickman figure).

If you examine `/tmp/` directory, you will find that it has a file like `test.sifz.BB318BD4.sif`, which contains all changes that were made after executing a plugin. For some reason executing a plugin replaces file saving location.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/82470022-file-not-saved-properly-after-executing-a-plugin?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by morevnaproject**
Fixes #949: Now saving/re-opening files for plugin operations are implemented by utilizing existing autobackup infrastructure.

### CODE REVIEW

**Comment by morevnaproject** [comment]
Please don't merge this yet. I am still investigating some things...

File: synfig-studio/src/gui/instance.cpp [hunk 1]
```diff
@@ -288,10 +295,48 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+		//
+		// QUICKHACK:
+		// Now dances with files :( (see https://github.com/synfig/synfig/issues/949)
+		//
+		// TODO: Replace copy operations with giomm???
+		//
+		// create a backup of original saved file
+		String backup_filename;
+		struct stat buf;
+		do {
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: Why not to use [Glib::mkstemp(std::string& filename_template)](https://developer.gnome.org/glibmm/2.60/group__FileUtils.html) here?

Comment (morevnaproject) [reply synfig-studio/src/gui/instance.cpp]: @ice0 I will try, thank you! ^__^

Comment (morevnaproject) [reply synfig-studio/src/gui/instance.cpp]: This wouldn't work, because it returns `file descriptor` (int), while I need `fstream`.
It is possible to get fstream from file descriptor, but it is non-standard - https://stackoverflow.com/questions/2746168/how-to-construct-a-c-fstream-from-a-posix-file-descriptor

File: synfig-studio/src/gui/instance.cpp [hunk 2]
```diff
@@ -274,30 +283,54 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+			
+				// Restore file copy
+				FileSystem::WriteStream::Handle stream = temporary_filesystem->get_write_stream(tmp_filename);
+				if (!stream)
+				{
+					synfig::error("run_plugin(): Unable to open file for write");
+				}
+				stream = FileSystem::WriteStream::Handle(new ZWriteStream(stream));
+				std::ifstream  infile(filename_processed, std::ios::binary);
+				*stream << infile.rdbuf();
```
Comment (morevnaproject) [inline synfig-studio/src/gui/instance.cpp]: @blackwarthog Can you please check - if this is correct way to copy-and-compress file?

**Comment by morevnaproject** [comment]
Ready for merge now. ^__^

File: synfig-studio/src/gui/instance.cpp [hunk 3]
```diff
@@ -238,69 +240,178 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+	FileSystemTemporary::Handle temporary_filesystem = FileSystemTemporary::Handle::cast_dynamic(get_canvas()->get_file_system());
+	String tmp_filename = temporary_filesystem->get_temporary_directory() + ETL_DIRECTORY_SEPARATOR + temporary_filesystem->get_temporary_filename_base();
 
-		synfigapp::PluginLauncher launcher(canvas);
+	Time cur_time;
+	cur_time = canvas->get_time();
 
-		Time cur_time;
-		cur_time = canvas->get_time();
+	// Create random filename
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: I propose to replace“random” with “temporary”.

File: synfig-studio/src/gui/instance.cpp [hunk 4]
```diff
@@ -238,69 +240,178 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+					"or restart Synfig Studio."),
+				_("Close"));
 
-		this->close();
+	} else {
 
-		if(canvas->count()!=1)
+		// Save file copy
+		String filename_ext = filename_extension(filename_original);
+		if (filename_ext=="")
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: Better to use "filename_ext.empty()"

File: synfig-studio/src/gui/instance.cpp [hunk 5]
```diff
@@ -238,69 +240,178 @@ studio::Instance::run_plugin(std::string plugin_path)
...
-			App::dialog_message_1b(
-					"ERROR",
-					_("The plugin operation has failed."),
-					_("This can be due to current file "
-						"being referenced by another composition that is already open, "
-						"or because of an internal error in Synfig Studio. Try closing "
-						"any compositions that might reference this file and try again, "
-						"or restart Synfig Studio."),
-					_("Close"));
+			synfig::error("run_plugin(): Unable to open file for reading");
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: Need to add filename just to understand what is happened.

File: synfig-studio/src/gui/instance.cpp [hunk 6]
```diff
@@ -238,69 +240,178 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+
+
+		bool result;
+		int exitcode;
+		String output;
+		String command = "";
+
+		// Path to python binary can be overridden
+		// with SYNFIG_PYTHON_BINARY env variable:
+		char* custom_python_binary=getenv("SYNFIG_PYTHON_BINARY");
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: const char*

File: synfig-studio/src/gui/instance.cpp [hunk 7]
```diff
@@ -238,69 +240,178 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+		if(custom_python_binary) {
+			command=custom_python_binary;
+			if (!App::check_python_version(command)) {
+				output="Error: You need to have Python 3 installed.";
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: _() ?

File: synfig-studio/src/gui/instance.cpp [hunk 8]
```diff
@@ -238,69 +240,178 @@ studio::Instance::run_plugin(std::string plugin_path)
...
+				{
+					command = python_path;
+					break;
+				}
 
-			one_moment.show();
+			}
 
+		}
+		if (command == "")
```
Comment (ice0) [inline synfig-studio/src/gui/instance.cpp]: command.empty()

**Comment by morevnaproject** [comment]
@ice0 Thank you for review, I have made all changes now. ^__^
