### PR TITLE
fix: couldn't create converter to spline tangent or spline width (regression)

### LINKED ISSUE #3532: Spline Tangent and Spline Width converters are broken in master
### Description
When trying to convert a node to "Spline Tangent" or "Spline Width" converter, Synfig throws a "Bad connection" error:
Image

### To Reproduce
1. Add a Circle layer
2. Right-click on any real value (e.g. Opacity)->Convert->Spline Tangent|Width

### Testing
Tested on: 5a4a58cf24019dc731a7b29c361e375a736e5f1c

This got broken fairy recently, I know that this commit works as expected: 842638c287a326cf67a946ab28dd3713f1a6e563
Perhaps this is a culprit: fddd3964ead305920ae2b0e6acc68b7b07268d77 (just a guess)

### PR DESCRIPTION
**Pull request by Stargazer10101**
Commit https://github.com/synfig/synfig/commit/fddd3964ead305920ae2b0e6acc68b7b07268d77 introduced a bad connection error when spline tangent and spline width converters are applied to a real parameter of a layer.

Fixes  #3532

### CODE REVIEW

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp [hunk 1]
```diff
@@ -104,10 +104,8 @@ ValueNode_BLineCalcTangent::operator()(Time t, Real amount)const
 	const ValueBase bline_value_node = (*bline_)(t);
 
 	const bool looped = bline_value_node.get_loop();
-	const int size = (int)bline.size();
-	if (size == 0)
-		return ValueBase();
-	const int count = looped ? size : size - 1;
+	int size = (int)bline.size();
+ 	int count = looped ? size : size - 1;
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp:108]: Why did you remove the `const`ness? `size` is immutable, isn't it? :)

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp [hunk 2]
```diff
@@ -104,10 +104,8 @@ ValueNode_BLineCalcTangent::operator()(Time t, Real amount)const
 	const ValueBase bline_value_node = (*bline_)(t);
 
 	const bool looped = bline_value_node.get_loop();
-	const int size = (int)bline.size();
-	if (size == 0)
-		return ValueBase();
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp:109]: Hmm... That's the problem. The code returns a `null` ValueBase without a type. Look how the next `if` returns value.

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp [hunk 3]
```diff
@@ -102,10 +102,8 @@ ValueNode_BLineCalcWidth::operator()(Time t, Real amount)const
 	const ValueBase bline_value_node = (*bline_)(t);
 
 	const bool looped = bline_value_node.get_loop();
-	const int size = (int)bline.size();
-	if (size == 0)
-		return ValueBase();
-	const int count = looped ? size : size - 1;
+	int size = (int)bline.size();
+ 	int count = looped ? size : size - 1;
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp:106]: `const`?

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp [hunk 4]
```diff
@@ -102,10 +102,8 @@ ValueNode_BLineCalcWidth::operator()(Time t, Real amount)const
 	const ValueBase bline_value_node = (*bline_)(t);
 
 	const bool looped = bline_value_node.get_loop();
-	const int size = (int)bline.size();
-	if (size == 0)
-		return ValueBase();
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp:107]: `return Real();` would be the correct statement here.

**Review by rodolforg — CHANGES_REQUESTED** [review]

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp (hunk 2 above)
Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp:109]: Hmm. So the if condition should return a typed ValueBase just like the next if condition. I'll make this change.

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp (hunk 4 above)
Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp:107]: Alright

**Comment by Stargazer10101** [comment]
Earlier I had simply undone the changes made to value node blinecalctangent and blinecalcwidth in the commit https://github.com/synfig/synfig/commit/fddd3964ead305920ae2b0e6acc68b7b07268d77, but based on the feedback received, I have now made the required changes.

> It is not a "crash". "Crash" is when the app suddenly closes and potentially losing or corrupting user data.

Got it

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp (hunk 1 above)
Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp]: Yes

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp [hunk 5]
```diff
@@ -103,9 +103,9 @@ ValueNode_BLineCalcWidth::operator()(Time t, Real amount)const
 
 	const bool looped = bline_value_node.get_loop();
 	const int size = (int)bline.size();
-	if (size == 0)
-		return ValueBase();
-	const int count = looped ? size : size - 1;
+ 	if (size == 0)
+ 		return Real();
+ 	const int count = looped ? size : size - 1;
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp:108]: There is a single space at start of each of these lines. Use tab for indentation.

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp [hunk 6]
```diff
@@ -105,9 +105,14 @@ ValueNode_BLineCalcTangent::operator()(Time t, Real amount)const
 
 	const bool looped = bline_value_node.get_loop();
 	const int size = (int)bline.size();
-	if (size == 0)
-		return ValueBase();
-	const int count = looped ? size : size - 1;
+ 	if (size == 0){
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp:108]: please add a single space before the `{`

**Review by rodolforg — CHANGES_REQUESTED** [review]
Thank you for your contribution!
Minor requests about code style.

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp (hunk 5 above)
Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp]: alright

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp (hunk 6 above)
Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp]: ok

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp [hunk 7]
```diff
@@ -104,7 +104,7 @@ ValueNode_BLineCalcWidth::operator()(Time t, Real amount)const
 	const bool looped = bline_value_node.get_loop();
 	const int size = (int)bline.size();
 	if (size == 0)
-		return ValueBase();
+		return Real();
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp:107]: remove trailing space...

Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp]: "Whoops! Can't believe that sneaky space got past me. Fixed it now—thanks for spotting it!"

Comment (Stargazer10101) [reply synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp]: Whoops! Can't believe that sneaky space got past me. Fixed it now—thanks for spotting it!

File: synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp [hunk 8]
```diff
@@ -105,9 +105,14 @@ ValueNode_BLineCalcTangent::operator()(Time t, Real amount)const
...
-		return ValueBase();
-	const int count = looped ? size : size - 1;
+	if (size == 0) {
+		Type &type(get_type());
+		if (type == type_angle)  return Angle();
+		if (type == type_real)   return Real();
+		if (type == type_vector) return Vector();
+	    return ValueBase();
+	}
+ 	const int count = looped ? size : size - 1;
```
Comment (rodolforg) [inline synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp:115]: sorry, there is still a leading space here

**Comment by Stargazer10101** [comment]
Now I think it's all fixed. I'm sorry about not paying attention to detail. Will be careful hereafter.

**Review by rodolforg — APPROVED** [review]

**Comment by Stargazer10101** [comment]
Kindly merge the pull request.
