### PR TITLE
fix(advanced_outline): incorrect width rendering on open outlines

### LINKED ISSUE #3645: Improper width rendering on unlooped outline
### Description

I found another regression in width rendering of advanced outline if the outline is open.  Check out this image:

Image

The vertexes and width points are placed in a way it would produce a mirrored output on top and bottom. Version 1.0.2 gives proper result, 1.5.3 renders the bottom part thicker than the top one.

### Affected versions
Everything since version 1.4.0 at least, works fine in 1.2.2.

Test-case file:
[IncorrectWidth.zip](https://github.com/user-attachments/files/23839364/IncorrectWidth.zip)

### PR DESCRIPTION
**Pull request by Abdelhadi-Wael**
fixes #3645

### CODE REVIEW

**Comment by Svarov-RZM** [comment]
Hey, thank you for looking into this, I know debugging cases like this is not a fun time.
I'll test it during the week and report back.

**Comment by Svarov-RZM** [comment]
Tested, everything's good, thank you!

@ice0 @rodolforg @BobSynfig
Guys, what practices do we have when merging? I recently got a development role and don't fully understand how should I go about this yet. Should I create a merge commit or squash and merge? I believe squash and merge is preferred, right?

File: synfig-core/src/modules/mod_geometry/advanced_outline.cpp [hunk 1]
```diff
@@ -203,7 +203,14 @@ namespace {
 			iterator i1 = lower_bound(p);
 			if (i1 == end())
 				{ clear(); return; }
-				
+
+			if (approximate_equal(i1->first, p)) {
+				erase(begin(), i1);
+				i1->second.side0 = side;
+				i1->second.pp0 = Vector(p, 0);
```
Comment (rodolforg) [inline synfig-core/src/modules/mod_geometry/advanced_outline.cpp:209]: You should change the iterator 'contents' before possibly invalidating it with `erase()`. So, move the `erase` code line to below the `i1->second.xxxx` code lines.

**Comment by rodolforg** [comment]
@Svarov-RZM , "squash and merge" is preferred when:
1. the PR is a single commit
2. the PR is made of a lot of commits and they have a lot of mistakes or drafts among them i.e. they were supposed to mean to be a single commit

If the multiple commits in the PR are organized to split into smaller steps/actions to accomplish the task proposed by the PR, we use "merge commit". In this case, each single commit should keep synfig code 'buildable' and usable.
But, before merging it, we ask to PR author to rebase the PR to current master branch, to do a beautiful merge (avoid messing commit tree and to author check if nothing 'clashes' (code lines or features/fixes) with the current state of PR.

@ice0  please correct me if I'm wrong.

File: synfig-core/src/modules/mod_geometry/advanced_outline.cpp [hunk 2]
```diff
@@ -247,7 +254,14 @@ namespace {
 			if (i1 == begin())
 				{ clear(); return; }
 			iterator i0 = i1; --i0;
-				
+
+			if (approximate_equal(i0->first, p)) {
+				erase(i1, end());
+				i0->second.side1 = side;
+				i0->second.pp1 = Vector(p, 0);
```
Comment (rodolforg) [inline synfig-core/src/modules/mod_geometry/advanced_outline.cpp]: Same here.

You should change the iterator 'contents' before possibly invalidating it with erase(). So, move the erase code line to below the i1->second.xxxx code lines.

**Review by rodolforg — CHANGES_REQUESTED** [review]

**Comment by ice0** [comment]
> But, before merging it, we ask to PR author to rebase the PR to current master branch, to do a beautiful merge (avoid messing commit tree and to author check if nothing 'clashes' (code lines or features/fixes) with the current state of PR.

Yes. All is correct.

@Svarov-RZM
Also this greatly helps when we doing `git bisect`. 

3. Make sure that all checks during the build have passed. 
If the build fails, it needs to be restarted. We merge the PR only if all checks have completed successfully.
4. If PR is approved and already rebased it should be merged first.

P.S. This PR can be squashed, so no rebase is required.
Also, you need to clean up the commit description if it doesn't carry any useful information.

image

**Comment by Svarov-RZM** [comment]
@ice0 Thank you for additional clarifications, it does help me very much as a newbie in this development thing.

@Abdelhadi-Wael PR is merged, thank you once again for addressing my issue.
