### PR TITLE
fix(animation): prevent out-of-bounds in next/prev keyframe navigation

### LINKED ISSUE #3423: "jump-[prev|next]-keyframe" action can jump past project's time range
### Description
OK, so this one is a very simple bug where you can go to the past/future keyframes that lie outside of current canvas' "Start Time"/"End Time". For example, if we have a project that starts on 3s and ends on 6s but there is a keyframe at, say, 1s you can get to it by pressing "jump-prev-keyframe" shortcut.

### To Reproduce
1. Open this file: 
[PastKeyframes.zip](https://github.com/user-attachments/files/17092838/PastKeyframes.zip)

2. It goes from 3s to 6s but there are keyframes past that you can access by pressing "jump-[prev|next]-keyframe" shortcut ('[' and ']' by default)

Notice that canvas view doesn't update, but layer tree does (look at the Circle's origin parameter) and name of the keyframe also changes on the canvas (e.g. "AT 0s") indicating that we indeed past the start of the project. 

### Expected behavior
Don't jump out of range, it can lead to confusion since you may end up animating on different time and wondering why nothing is happening. So when you hit "jump-[prev|next]-keyframe" shortcut it should remain on the first/last keyframe that lies in the range of project's "Start/End Time".

### PR DESCRIPTION
**Pull request by Abdelhadi-Wael**
Ensure keyframe navigation stays within the valid range by checking 
against the start and end times.

fix #3423

### CODE REVIEW

File: synfig-studio/src/synfigapp/canvasinterface.cpp [hunk 1]
```diff
@@ -674,6 +674,12 @@ CanvasInterface::jump_to_next_keyframe()
 	KeyframeList::iterator iter;
 	if (get_canvas()->keyframe_list().find_next(get_time(), iter)) {
 		synfig::Keyframe keyframe(*iter);
+		synfig::Time end_time = get_canvas()->rend_desc().get_time_end();
+		// Ensure we don't go past the End Time
+		if (keyframe.get_time() > end_time) {
+			synfig::warning("Next keyframe is out of range (beyond End Time). Staying within limits.");
```
Comment (rodolforg) [inline synfig-studio/src/synfigapp/canvasinterface.cpp:680]: Allow message localization: surround string with `_()` macro.

File: synfig-studio/src/synfigapp/canvasinterface.cpp [hunk 2]
```diff
@@ -692,6 +698,12 @@ CanvasInterface::jump_to_prev_keyframe()
 	{
 		//synfig::Keyframe keyframe(*get_canvas()->keyframe_list().find_prev(get_time()));
 		synfig::Keyframe keyframe(*iter);
+		// Ensure we don't go past the Start Time
+		synfig::Time start_time = get_canvas()->rend_desc().get_time_start();
+		if (keyframe.get_time() < start_time) {
+			synfig::warning("Previous keyframe is out of range (before Start Time). Staying within limits.");
```
Comment (rodolforg) [inline synfig-studio/src/synfigapp/canvasinterface.cpp:704]: Allow message localization: surround string with `_()` macro

**Review by rodolforg — CHANGES_REQUESTED** [review]
Thank you.

I wonder if we should:
1. provide a GUI warning message
2. disable the button when unavailable :P If so, the button should monitor changes in current time and canvas time boundaries.
3. give additional help in the message: "You can change the time span in the canvas settings" or something like that.

@Svarov-RZM @morevnaproject @ice0

**Comment by Abdelhadi-Wael** [comment]
Done

**Comment by ice0** [comment]
> Done

Looks good, but could you check the previous message from Rodolfo?

**Comment by Abdelhadi-Wael** [comment]
> Looks good, but could you check the previous message from Rodolfo (with his suggestions for improvement)?

sure should i do all 3 ?

**Review by rodolforg — APPROVED** [review]

**Comment by Svarov-RZM** [comment]
@Abdelhadi-Wael
Hey! Sorry it took me a year to return to this but now I have powers to merge things, so can you please rebase? I'll give it one more test and then merge if everything's alright.

**Comment by Abdelhadi-Wael** [comment]
> @Abdelhadi-Wael Hey! Sorry it took me a year to return to this but now I have powers to merge things, so can you please rebase? I'll give it one more test and then merge if everything's alright.

Hi @Svarov-RZM, good to see you It is rebased now :)

**Comment by Svarov-RZM** [comment]
Everything works as expected.
PR's merged, thank you!
