### PR TITLE
 Fix "Edit image in external tool" command for workarea

### LINKED ISSUE #810: "Edit image in external tool" does not works correctly when called from workarea
@ankit-kumar-dwivedi When I right-click image on workarea I see "Open file" menu entry, which is expected to behave the same as "Edit image in external tool" command. But when I click it, Synfig opens associated image viewer, not the editor app specified in preferences.

screenshot_001

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72660160-edit-image-in-external-tool-does-not-works-correctly-when-called-from-workarea?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
Fixes #810.  "Edit image in external tool" now works correctly when called from workarea. Replaced vector with set for fast find operation. created a function for confirming if the uri belongs to image layer or not.

@morevnaproject please review :)

### CODE REVIEW

File: synfig-studio/src/gui/instance.cpp [hunk 1]
```diff
@@ -1766,7 +1786,7 @@ Instance::add_special_layer_actions_to_group(const Glib::RefPtr<Gtk::ActionGroup
 	{
 		String action_name = etl::strprintf("special-action-open-file-%d", index);
 		//if the import layer is type image 
-		if(std::find(img_ext.begin(), img_ext.end(), filename_extension(i->second)) != img_ext.end())
+		if(is_img(filename_extension(i->second)))
```
Comment (morevnaproject) [inline synfig-studio/src/gui/instance.cpp]: This makes possible to remove the following line above (at the beginning of add_special_layer_actions_to_group() function) ^__^ -
```vector <String> img_ext{".jpg",".jpeg",".png",".bmp",".gif"};```

Comment (ankit-kumar-dwivedi) [reply synfig-studio/src/gui/instance.cpp]: Ah it's embarrassing

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Done Changes!

**Comment by morevnaproject** [comment]
Testing now! ^__^

**Comment by morevnaproject** [comment]
Works perfectly now. Thank you! ^__^
