### PR TITLE
Fix #1140: Clicking "Ignore" button doesn't removes backup

### LINKED ISSUE #1140: Autobackup restore: clicking "Ignore" button doesn't removes backup
Synfig version: Master branch, commit e8e7b8

When Synfig crashes it suggests to restore file saved via autobackup.

It offers two options - "Ignore" and "Recover". When clicking "Ignore" it should remove (discard) autobackup file. But this doesn't happens - choose "Ignore", then close Synfig, reopen again, and it will show you suggestion to restore autobackup again.

screenshot_010

Expected behavior: clicking "Ignore" button should remove (discard) autobackup file.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/87902451-autobackup-restore-clicking-ignore-button-doesn-t-removes-backup?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F321991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by morevnaproject**
The issue #1140 introduced in 28db040 -now we need to manually call `discard_changes()` when `FilesystemTemporary` destroyed.

### CODE REVIEW

File: synfig-studio/src/gui/autorecover.cpp [hunk 1]
```diff
@@ -164,8 +164,11 @@ AutoRecover::clear_backups()
 			// FileSystemTemporary will clear opened temporary files in destructor
 			String filename = App::get_temporary_directory() + ETL_DIRECTORY_SEPARATOR + *i;
 			bool s = false;
-			try { s = FileSystemTemporary("").open_temporary(filename); }
-			catch (...) { }
+			try {
+				FileSystemTemporary temporary_filesystem = FileSystemTemporary("");
+				s = temporary_filesystem.open_temporary(filename);
+				temporary_filesystem.discard_changes();
+			} catch (...) { }
```
Comment (ice0) [inline synfig-studio/src/gui/autorecover.cpp]: I think it is better to add synfig::warning on the exception. (Just to know what something bad is happened)

**Comment by ice0** [comment]
Merged. Thank you!
